name: deploy client
on:
  push:
    branches:
      - develop
      - main
      - "feature/**"
    # paths:
    #   - client/**
    #   - .github/workflows/develop-client.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup pnpm
        run: pnpm install


      # - name: Setup server
      #   run: make up
      #   working-directory: server
      #   env:
      #     DB_DATABASE: ${{ secrets.DB_DATABASE }}
      #     DB_HOST: ${{ secrets.DB_HOST }}
      #     DB_USER: ${{ secrets.DB_USER }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB_PORT: ${{ secrets.DB_PORT }}
      #     ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      #     PORT: ${{ secrets.PORT }}

      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_SERVER_URL: http://localhost:8080
          NEXT_PUBLIC_API_KEY: ${{secrets.NEXT_PUBLIC_API_KEY}}
          NEXT_PUBLIC_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_AUTH_DOMAIN}}
          NEXT_PUBLIC_PROJECT_ID: ${{secrets. NEXT_PUBLIC_PROJECT_ID}}
          NEXT_PUBLIC_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_STORAGE_BUCKET}}
          NEXT_PUBLIC_MESSAGIN_SENDER_ID: ${{secrets.NEXT_PUBLIC_MESSAGIN_SENDER_ID}}
          NEXT_PUBLIC_APP_ID: ${{secrets.NEXT_PUBLIC_APP_ID}}
          NEXT_MEASUREMENT_ID: ${{secrets.NEXT_MEASUREMENT_ID}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
          FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
          FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
