name: deploy server

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
    paths:
      - server/**
      - .github/workflows/develop-server.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
